### ISSUE TITLE
multiple users?

### ISSUE THREAD

**Issue by AcidEdge** [RpDp-git/PiDisplaySleep#3]
Sorry, i'm really new with programming. Would it be possible to have the module us 2 different ip's to look for?  would like it to be able to tell if either my wife or I are home.

**Comment by RpDp-git** [comment]
Sure. I highly encourage you try it as an excercise if you are new to programming. To start, try making the ip variable into a list of ip addresses you need. And make a nested loop in the main loop to go iterate through the list.
