### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by zapperiopa** [RpDp-git/PiDisplaySleep#5]
I'm not good with python, but check if hostname is active on network?
In case of DHCP change of IP.

hostname="samsung_s10"
nmap_out=str(popen('nmap -sP '+hostname).read())

Could work?

Great idea for module, just what I want. :)

**Comment by RpDp-git** [comment]
Sounds nice. Maybe you can start your branch for it. I think a better idea is MAC address as some devices usually dont have well defined host names. Or you could do a DHCP reservation for your MAC address on your router. Then no extra work is needed on this code.
